import { SlashCommandBuilder, EmbedBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle } from 'discord.js';

// ─── Colour palette ───────────────────────────────────────────────────────────
const COLOR = {
  user:    0x5865F2,
  server:  0xFEE75C,
  example: 0x2f3136,
};

// ─── Placeholder data (single source of truth) ───────────────────────────────
const PLACEHOLDERS = {
  user: [
    { ph: '{user}',               ar: 'منشن العضو', desc: '@mention — `<@id>`' },
    { ph: '{user.mention}',       ar: 'اسم الآخر لـ {user}', desc: 'Alias for `{user}`' },
    { ph: '{user.name}',          ar: 'اسم العضو النصي', desc: 'Plain username' },
    { ph: '{user.tag}',           ar: 'العلامة القديمة بصيغة `username#0000`', desc: '`username#0000`  (legacy discriminator format)' },
    { ph: '{user.id}',            ar: 'معرّف Discord الرقمي', desc: 'Numeric Discord user ID' },
    { ph: '{user.discriminator}', ar: 'الرقم الرباعي أو `0` للأسماء الجديدة', desc: '4-digit tag or `0` for new usernames' },
    { ph: '{user.avatar}',        ar: 'رابط الصورة الرمزية (PNG 256px)', desc: 'Avatar URL  *(PNG 256px — works in Image / Thumbnail / Icon URL fields)*' },
    { ph: '{user.created_at}',    ar: 'تاريخ إنشاء الحساب', desc: 'Account creation date  *(locale string)*' },
    { ph: '{account_age}',        ar: 'عمر الحساب بالأيام', desc: 'Account age in **days**' },
  ],
  member: [
    { ph: '{joined_at}',     ar: 'تاريخ انضمام العضو للخادم', desc: 'Date the member joined this server  *(locale string)*' },
    { ph: '{join_pos}',      ar: 'موضع الانضمام (مثال: 42)', desc: 'Join position  *(e.g. 42 — provided by the welcome event)*' },
    { ph: '{user.roles}',    ar: 'قائمة أسماء الأدوار مفصولة بفواصل', desc: 'Comma-separated list of role names  *(highest first, excludes @everyone)*' },
    { ph: '{user.top_role}', ar: 'اسم أعلى دور للعضو', desc: "Name of the member's highest role" },
  ],
  server: [
    { ph: '{server}',            ar: 'اسم الخادم', desc: 'Server name' },
    { ph: '{server.name}',       ar: 'اسم الخادم (اسم آخر)', desc: 'Alias for `{server}`' },
    { ph: '{server.id}',         ar: 'معرّف الخادم الرقمي', desc: 'Numeric guild ID' },
    { ph: '{server.icon}',       ar: 'رابط أيقونة الخادم (PNG 256px)', desc: 'Server icon URL  *(PNG 256px — works in Icon URL fields)*' },
    { ph: '{server.owner_id}',   ar: 'معرّف مالك الخادم', desc: 'User ID of the server owner' },
    { ph: '{server.created_at}', ar: 'تاريخ إنشاء الخادم', desc: 'Server creation date  *(locale string)*' },
    { ph: '{member_count}',      ar: 'العدد الإجمالي للأعضاء', desc: 'Total member count' },
    { ph: '{boost_count}',       ar: 'عدد الـ Boosts النشطة', desc: 'Number of active boosts' },
    { ph: '{boost_level}',       ar: 'مستوى التعزيز (0-3)', desc: 'Boost tier  `0` `1` `2` `3`' },
  ],
  channel: [
    { ph: '{channel.name}',    ar: 'اسم القناة (بدون #)', desc: 'Channel name  *(no # prefix)*' },
    { ph: '{channel.id}',      ar: 'معرّف القناة الرقمي', desc: 'Numeric channel ID' },
    { ph: '{channel.mention}', ar: 'منشن القناة بصيغة `<#id>`', desc: 'Clickable channel mention  `<#id>`' },
  ],
  partner: [
    { ph: '{invite.code}',  ar: 'رمز الدعوة المستخدمة (ينشئها الشريك عند الانضمام)', desc: 'Invite code used by the member who joined — generated by partner' },
    { ph: '{invite.uses}',  ar: 'إجمالي عدد استخدامات الدعوة', desc: 'Total number of uses for the invite code' },
    { ph: '{partner.name}', ar: 'اسم إيمبد الشريك المرتبط بالدعوة', desc: 'Name of the partner embed linked to this invite code' },
  ],
  special: [
    { ph: '{timestamp}',    ar: 'الوقت الحالي كـ Discord timestamp',  desc: 'Current time as a **live** Discord relative timestamp  `<t:unix:R>`' },
    { ph: '{choose:A|B|C}', ar: 'اختيار عشوائي من الخيارات المفصولة بـ |', desc: 'Randomly picks one option — add as many pipe-separated options as you want' },
  ],
};

// ─── Helpers ──────────────────────────────────────────────────────────────────

function fmt(list) {
  return list.map(({ ph, ar }) => `\`${ph}\` → ${ar}`).join('\n');
}

function pageFooter(interaction, page, total) {
  return {
    text: `صفحة ${page}/${total}  •  استخدم /embed_help للعودة | Page ${page}/${total}  •  /embed manager to open the editor`,
    iconURL: interaction.guild?.iconURL({ extension: 'png', size: 64 }) ?? undefined,
  };
}

// ─── Page builders ────────────────────────────────────────────────────────────

const PAGE_COLORS = [0x5865F2, 0xFEE75C, 0x2f3136, 0xFF6B6B]; // Blurple, Gold, Dark Grey, Red

export function buildPages(interaction) {
  // ── Page 1: Basic Placeholders (User) ──────────────────────────────────────
  const p1 = new EmbedBuilder()
    .setColor(PAGE_COLORS[0])
    .setTitle('👤 المتغيرات الأساسية (المستخدم) • Basic Placeholders (User)')
    .setDescription(
      'يتم استبدال المتغيرات ببيانات مباشرة عند إرسال الإيمبد.\n' +
      'تعمل في **كل** حقل نصي وفي كل مكان تقريباً!\n\u200b'
    )
    .addFields(
      { name: '👤 متغيرات المستخدم • User Variables',   value: fmt(PLACEHOLDERS.user),   inline: false },
      { name: '\u200b',    value: '\u200b',                  inline: false }
    )
    .setFooter(pageFooter(interaction, 1, 4));

  // ── Page 2: Server & Member Data ──────────────────────────────────────────
  const p2 = new EmbedBuilder()
    .setColor(PAGE_COLORS[1])
    .setTitle('🏠 بيانات الخادم والعضو • Server & Member Data')
    .addFields(
      { name: '🏠 متغيرات الخادم • Server Variables', value: fmt(PLACEHOLDERS.server), inline: false },
      { name: '\u200b',    value: '\u200b',                  inline: false },
      { name: '🎖️ متغيرات العضو • Member Variables', value: fmt(PLACEHOLDERS.member), inline: false }
    )
    .setFooter(pageFooter(interaction, 2, 4));

  // ── Page 3: Channel & Special (Random Choice) ─────────────────────────────
  const p3 = new EmbedBuilder()
    .setColor(PAGE_COLORS[2])
    .setTitle('🎲 القنوات و المنطق الديناميكي • Channels & Dynamic Logic')
    .addFields(
      {
        name:  '📍 متغيرات القناة • Channel Variables',
        value: fmt(PLACEHOLDERS.channel),
        inline: false,
      },
      { name: '\u200b', value: '\u200b', inline: false },
      {
        name:  '🎲 الاختيار العشوائي • Random Choice',
        value: fmt([{ ph: '{choose:A|B|C}', ar: 'اختيار عشوائي من 3 حلول أو أكثر', desc: 'Randomly picks one option' }]),
        inline: false,
      },
      {
        name: '📝 مثال • Example',
        value: '```\n{choose:مرحباً|أهلاً وسهلاً|أهلا}, {user.name}!\nأنت العضو #{join_pos}\n```',
        inline: false,
      }
    )
    .setFooter(pageFooter(interaction, 3, 4));

  // ── Page 4: Partner Invite Variables (Enhanced) ────────────────────────────
  const p4 = new EmbedBuilder()
    .setColor(PAGE_COLORS[3])
    .setTitle('🤝 متغيرات الشريك والدعوات • Partner & Invite Variables')
    .setDescription(
      '**المتغيرات الخاصة للإيمبدات المرتبطة برموز الدعوات.**\n' +
      'عندما ينضم عضو باستخدام دعوة مرتبطة بإيمبد شريك، تصبح هذه المتغيرات متاحة:\n\u200b'
    )
    .addFields(
      { name: '🔗 بيانات الشريك • Partner Data', value: fmt(PLACEHOLDERS.partner), inline: false },
      { name: '\u200b', value: '\u200b', inline: false },
      {
        name: '📝 مثال كامل • Complete Example',
        value: '```\n✨ مرحباً, {user.name}! ✨\nانضممت عبر: `{invite.code}`\nهذه الدعوة استُخدمت {invite.uses} مرات!\nالشريك: {partner.name}\n```',
        inline: false,
      },
      {
        name: '🔍 شرح مفصل • Detailed Explanation',
        value: 
          '• `{invite.code}` 🔗 **رمز الدعوة**\n   الكود الذي استخدمه العضو للانضمام\n\n' +
          '• `{invite.uses}` 📊 **عدد الاستخدامات**\n   كم مرة تمت استخدام هذه الدعوة\n\n' +
          '• `{partner.name}` 🎯 **اسم إيمبد الشريك**\n   اسم الإيمبد المرتبط برمز الدعوة\n\n' +
          '**الخطوات:**\n' +
          '1️⃣ أنشئ إيمبد جديد (مثال: "Partner Welcome")\n' +
          '2️⃣ استخدم `/embed bind name:Partner Welcome invite_code:YOUR_CODE`\n' +
          '3️⃣ عندما ينضم عضو برمز الدعوة، سيرى الإيمبد مع المتغيرات المدرجة أعلاه\n',
        inline: false,
      }
    )
    .setFooter(pageFooter(interaction, 4, 4));

  return [p1, p2, p3, p4];
}

// ─── Command ──────────────────────────────────────────────────────────────────

function buildButtonRow(currentPage, totalPages) {
  const prevButton = new ButtonBuilder()
    .setCustomId('help_prev')
    .setLabel('⬅️ Previous')
    .setStyle(ButtonStyle.Secondary)
    .setDisabled(currentPage === 0);

  const nextButton = new ButtonBuilder()
    .setCustomId('help_next')
    .setLabel('Next ➡️')
    .setStyle(ButtonStyle.Primary)
    .setDisabled(currentPage === totalPages - 1);

  const closeButton = new ButtonBuilder()
    .setCustomId('help_close')
    .setLabel('❌ Close')
    .setStyle(ButtonStyle.Danger);

  return new ActionRowBuilder().addComponents(prevButton, nextButton, closeButton);
}

export default {
  data: new SlashCommandBuilder()
    .setName('embed_help')
    .setDescription('عرض جميع المتغيرات المدعومة • Shows every placeholder supported by Embed Engine V3.'),

  async execute(interaction) {
    const pages = buildPages(interaction);
    let currentPage = 0;
    const totalPages = pages.length;

    const response = await interaction.reply({
      embeds: [pages[currentPage]],
      components: [buildButtonRow(currentPage, totalPages)],
      flags: [MessageFlags.Ephemeral],
    });

    // Create message component collector
    const collector = response.createMessageComponentCollector({
      time: 15 * 60 * 1000, // 15 minutes
    });

    collector.on('collect', async (buttonInteraction) => {
      // Only allow the user who initiated the help command to interact
      if (buttonInteraction.user.id !== interaction.user.id) {
        return buttonInteraction.reply({
          content: '❌ You can only use buttons on your own help message.',
          flags: [MessageFlags.Ephemeral],
        });
      }

      if (buttonInteraction.customId === 'help_prev') {
        currentPage = Math.max(0, currentPage - 1);
      } else if (buttonInteraction.customId === 'help_next') {
        currentPage = Math.min(totalPages - 1, currentPage + 1);
      } else if (buttonInteraction.customId === 'help_close') {
        collector.stop();
        return buttonInteraction.reply({
          content: '❌ Help closed.',
          flags: [MessageFlags.Ephemeral],
        });
      }

      await buttonInteraction.update({
        embeds: [pages[currentPage]],
        components: [buildButtonRow(currentPage, totalPages)],
      });
    });

    collector.on('end', () => {
      // Optionally remove components when collector times out
      response.edit({ components: [] }).catch(() => {});
    });
  },
};